- name: ec2 Launch
  hosts: localhost
  connection: local
  tasks:
  - name: Lanuching ec2
    ec2:
      instance_type: t2.micro
      key_name: WordPress_site
      image: <AMI ID> 
      region: us-west-2
      group: default	  
      count: 1
	  vpc_subnet_id: <subnet id>
	  wait : yes
	  assign_public_ip: yes
	  aws_access_key: <*****>
      aws_secret_key: <*****>
